permalink: /:year/:month/:title.html
markdown: kramdown

github: [metadata]

kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

sass:
  sass_dir: src/scss
  style: :compressed

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - src
  - script
  - _drafts
  - design
  - node_modules
  - bower_components
  - bower.json

feed:
  path: atom.xml

name: flat - The personal website of Steve Agalloco
title: flat
description: before it was round
tagline: 'The personal website of Steve Agalloco'
url: http://beforeitwasround.com
baseurl: /

author: Steve Agalloco
email: steve.agalloco@gmail.com

twitter:
  username: stveaux
